services:
  perfsonar-testpoint:
    build:
      context: .
      dockerfile: Dockerfile-perfsonar-testpoint
    container_name: perfsonar-testpoint
    network_mode: "host"
    image: kthare10/perfsonar-testpoint:systemd
    cgroup: host
    tty: true
    stdin_open: true
    environment:
      - HOSTS=${HOSTS:-23.134.232.51}
      - HOST_IP=${HOST_IP:-23.134.232.51}
      - AUTH_TOKEN=${AUTH_TOKEN:-changeme}  # Change this before deployment
      - ARCHIVE=${ARCHIVE:-/usr/src/app/config.json}
      - URL=${URL:-http://23.134.232.51:8000/api/save/}
      - TZ=${TZ:-UTC}
      - CRON_EXPRESSION=${CRON_EXPRESSION:-0 */2 * * *}
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./compose/config.json:/usr/src/app/config.json
      - ./pscheduler_test_runner.py:/usr/src/app/periodic.py
      - ./compose/bootstrap_cron.sh:/etc/cron.hourly/bootstrap_cron.sh
      - ./data_testpoint:/data  # Results & logs outside
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./compose/psconfig:/etc/perfsonar/psconfig
    restart: always

  perfsonar-tool:
    build:
      context: .
      dockerfile: Dockerfile-perfsonar-tool
    container_name: perfsonar-tool
    image: kthare10/perfsonar-tool
    tty: true
    stdin_open: true
    environment:
      - HOSTS=23.134.232.210 23.134.232.242  # Correct syntax
      - TZ=UTC
      - INTERVAL=0 */2 * * * # Example: Run every 2 hours
    volumes:
      - ./data_tools:/data  # Results & logs outside
    restart: always
