FROM perfsonar/testpoint:systemd

LABEL maintainer="komal.thareja@gmail.com"

RUN apt update && apt install -y cron

# Copy your Python script and entrypoint script
COPY pscheduler_test_runner.py /usr/src/app/periodic.py
COPY custom-cron.sh /usr/src/app/

RUN chmod +x /usr/src/app/custom-cron.sh

# Copy systemd service file
COPY custom-cron.service /etc/systemd/system/custom-cron.service

# Enable the service
RUN systemctl enable custom-cron.service
