services:
  perfsonar-testpoint:
    build:
      context: .
      dockerfile: Dockerfile-perfsonar-testpoint
    container_name: perfsonar-testpoint
    network_mode: "host"
    image: kthare10/perfsonar-testpoint:systemd
    cgroup: host
    tty: true
    stdin_open: true
    environment:
      - HOSTS=${HOSTS:-23.134.232.50@shore-STAR}
      - AUTH_TOKEN=${AUTH_TOKEN:-changeme}  # Change this before deployment
      - ARCHIVE_URLS=${ARCHIVE_URLS:-https://localhost:8443/ps}
      - TZ=${TZ:-UTC}
      - CRON_EXPRESSION=${CRON_EXPRESSION:-0 */2 * * *}
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./pscheduler_test_runner.py:/usr/src/app/periodic.py
      - ./compose/bootstrap_cron.sh:/etc/cron.hourly/bootstrap_cron.sh
      - ./data_testpoint:/data  # Results & logs outside
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./compose/psconfig:/etc/perfsonar/psconfig
    restart: always